version: 2.0

defaults: &defaults
  docker:
    - image: circleci/android:api-26-alpha
  working_directory: ~/code
  environment:
    JVM_OPTS: -Xmx3200m
    TERM: dumb

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew dependencies --no-daemon
      - run:
          name: Run tests for debug build and generate reports
          command: ./gradlew build jacocoTestReport --no-daemon
      - run:
          name: Upload reports to Codecov
          command: bash <(curl -s https://codecov.io/bash)
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - store_artifacts:
          path: app/build/outputs/apk
          destination: apks
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      - persist_to_workspace:
          root: .
          paths:
            - .gradle
            - build
            - app/build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build